#!/usr/bin/env python

from flic import flic
import rospy
from std_msgs.msg import String
from flic_button.msg import press_event, connectivity_event

# adapted from https://github.com/50ButtonsEach/fliclib-linux-dist/blob/master/samples/python/main.py

# check flic::client::button::ButtonEventListener Class Reference
class ButtonEventListener(flic.ButtonEventListener):

    def __init__(self):
        super(ButtonEventListener,self).__init__()
        self.press_pub = rospy.Publisher('~press_events', press_event, queue_size=10)
        self.connection_pub = rospy.Publisher('~connection_events', connectivity_event, queue_size=10)

    def onReady(self, deviceId):
        print "ready", deviceId
        
    def deviceId2Name(self, deviceId):
        assert isinstance(deviceId, str)
        if deviceId == "80:E4:DA:71:15:99":
            return "FOO"
        if deviceId == "80:E4:DA:71:19:9A":
            return "BAR"
        return deviceId
                
    def getHash(self):
        return "main"

    def onBatteryStatus(self, deviceId, battery):
        print "Battery", battery

        
    def onConnecting(self, deviceId):
        print "Connecting", deviceId 
        msg = connectivity_event(deviceId =  deviceId)
        msg.connected = True
        self.sendMsg(self.connection_pub, msg)
     
    def onDisconnect(self, deviceId):
        print "Disconnected", deviceId
        msg = connectivity_event(deviceId =  deviceId)
        msg.disconnected = True
        self.sendMsg(self.connection_pub, msg)
     
    def onButtonSingleOrDoubleClickOrHold(self, deviceId, queued, timeDiff, isSingle, isDouble, isHold):
        msg = press_event(deviceId = deviceId)
        msg.isSingle = isSingle
        msg.isDouble = isDouble
        msg.isHold = isHold
        self.sendMsg(self.press_pub, msg)
     
    def onButtonUpOrDown(self, deviceId, queued, timeDiff, isUp, isDown):
        msg = press_event(deviceId =  deviceId)
        msg.isUp = isUp
        msg.isDown = isDown
        self.sendMsg(self.press_pub, msg)
       
        
    def sendMsg(self, publisher, msg):
        assert(isinstance(msg, press_event) or isinstance(msg, connectivity_event))
        msg.stamp = rospy.get_rostime()
        msg.name = self.deviceId2Name(msg.deviceId)
        
        publisher.publish(msg)
        rospy.sleep(0.2)



def addButtonEventListener(button):
    button.addButtonEventListener(buttonEventListener)

class ButtonListener(flic.ButtonListener):
    def getHash(self):
        return "main"

    def onButtonDiscover(self, button):
        addButtonEventListener(button)


class InitializedCallback(flic.CallbackVoid):
    def callback(self):
        # print("Initialized")
        manager = client.getManager()
        buttons = manager.getButtons()
        try:
            for button in buttons:
                # print button.getDeviceId()
                addButtonEventListener(button)
            manager.addButtonListener(buttonListener)
        except:
            pass

class UninitializedCallback(flic.CallbackBool):
    def callback(self):
        print("Uninitialized")


if __name__ == "__main__":
    
    rospy.init_node("flic_bridge")
    
    client = flic.Client()
    buttonEventListener = ButtonEventListener()
    buttonListener = ButtonListener()

    init = InitializedCallback()
    uninit =  UninitializedCallback()
    client.start(init.getCallback(), uninit.getCallback())

    client.run()
    
    
    
